### ISSUE TITLE
Rework the main background picture

### ISSUE THREAD

**Issue by andreybakanovsky** [widefix/pocketmoney#220]
The original:
![Image](https://github.com/widefix/pocketmoney/assets/81028629/dfd494fc-6855-45aa-95ac-ee607db3ceb9)

**Comment by andreybakanovsky** [comment]
Current:

![Image](https://github.com/widefix/pocketmoney/assets/81028629/a89f8f99-dff8-4597-b7b7-72d983a31fb0)

**Comment by ka8725** [comment]
No idea where this original image came from even though it looks good. The current bg is the original.
