### ISSUE TITLE
Remove “Account owner:” on account

### ISSUE THREAD

**Issue by VladislavSokov** [widefix/pocketmoney#309]
![Image](https://github.com/widefix/pocketmoney/assets/62177364/402c0ef3-d13b-42d7-947f-6f66ac19e6d4)

**Comment by ka8725** [comment]
@VladislavSokov there is still issue with public share - https://budgetingkid.com/public_accounts/xXU8jg6QmFM3wjQZ9jv3f6c9l58yLBDo7SHj-6K9AAg
